services:
  kalka-app:
    image: lemeshev/kalka:latest
    ports:
      - "3000:3000"
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Я прибрав 'version', виправив '--cleanup' і додав '--debug', 
    # щоб ти бачив кожен крок перевірки в логах
    command: --interval 30 --cleanup --debug